name: comprobar-lambda

on:
  workflow_dispatch:

jobs:
  comprobar:
    runs-on: ubuntu-latest

    steps:
      - name: Credenciales temporales
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Comprobar Lambda
        run: |
          aws lambda get-function \
            --function-name inf384-lab3 \
            --region us-east-1
